/**
 * Shell completions generator (issue #107).
 *
 * Single source of truth: the FLAGS table below drives every shell script AND
 * the drift-guard test (test/completions.test.mjs) that diffs it against the
 * flags actually parsed in bin/cli.mjs. Adding a flag in parseArgs without
 * updating this table fails the test — and vice versa.
 *
 * Static generation only: no runtime dependency, `mdss completions <shell>`
 * prints a self-contained script to stdout.
 */

export type FlagKind = 'flag' | 'value' | 'file' | 'dir' | 'number';

export interface FlagSpec {
  /** Primary long form, e.g. "--index-dir". */
  name: string;
  alias?: string;
  kind: FlagKind;
}

/** Every option bin/cli.mjs parseArgs understands (issue #107 drift guard). */
export const FLAGS: FlagSpec[] = [
  // boolean switches
  { name: '--json', kind: 'flag' },
  { name: '--semantic', kind: 'flag' },
  { name: '--offline', kind: 'flag' },
  { name: '--watch', kind: 'flag' },
  { name: '--watch-debug', kind: 'flag' },
  { name: '--no-ui', kind: 'flag' },
  { name: '--rerank', kind: 'flag' },
  { name: '--explain', kind: 'flag' },
  { name: '--interactive', alias: '-i', kind: 'flag' },
  { name: '--list-tools', kind: 'flag' },
  { name: '--no-vectors', alias: '--no-vector', kind: 'flag' },
  { name: '--no-query-cache', kind: 'flag' },
  { name: '--recency', kind: 'number' },
  { name: '--health-public', kind: 'flag' },
  { name: '--allow-unsecured', kind: 'flag' },
  { name: '--ann', kind: 'flag' },
  { name: '--canonical', kind: 'flag' },
  { name: '--rag', kind: 'flag' },
  { name: '--auto-tag', kind: 'flag' },
  { name: '--auto-summarize', kind: 'flag' },
  { name: '--help', alias: '-h', kind: 'flag' },
  { name: '--version', kind: 'flag' },
  { name: '--open', kind: 'flag' }, // optional N consumed by parseArgs itself
  { name: '--fix', kind: 'flag' },
  { name: '--dry-run', kind: 'flag' },
  // values
  { name: '--workers', kind: 'number' },
  { name: '--config', kind: 'file' },
  { name: '--format', kind: 'value' },
  { name: '--output', alias: '-o', kind: 'file' },
  { name: '--db', kind: 'dir' },
  { name: '--vault', kind: 'dir' },
  { name: '--index-dir', kind: 'dir' },
  { name: '--cache-dir', kind: 'dir' },
  { name: '--model', kind: 'value' },
  { name: '--k', kind: 'number' },
  { name: '--max-per-file', kind: 'number' },
  { name: '--max-per-doc', kind: 'number' },
  { name: '--target-tokens', kind: 'number' },
  { name: '--port', kind: 'number' },
  { name: '--host', kind: 'value' },
  { name: '--api-key', kind: 'value' },
  { name: '--api-key-file', kind: 'file' },
  { name: '--allowed-host', kind: 'value' },
  { name: '--cors-origin', kind: 'value' },
  { name: '--watch-delay', kind: 'number' },
  { name: '--watch-interval', kind: 'number' },
  { name: '--rate-limit', kind: 'number' },
  { name: '--max-concurrency', kind: 'number' },
  { name: '--since', kind: 'value' },
  { name: '--path', kind: 'value' },
  { name: '--ignore', kind: 'value' },
  { name: '--tag', kind: 'value' },
  { name: '--nprobe', kind: 'number' },
  { name: '--project', kind: 'value' },
  { name: '--type', kind: 'value' },
  { name: '--status', kind: 'value' },
  { name: '--graph-boost', kind: 'number' },
  { name: '--filter', kind: 'value' },
  { name: '--quantize', kind: 'value' },
  { name: '--llm-endpoint', kind: 'value' },
  { name: '--llm-model', kind: 'value' },
  { name: '--system-prompt', kind: 'value' },
];

export const COMMANDS = [
  'index', 'stats', 'check', 'doctor', 'export', 'search',
  'ask', 'tui', 'serve', 'mcp', 'models', 'completions',
];

export const COMPLETION_SHELLS = ['bash', 'zsh', 'fish', 'powershell'] as const;
export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

const DIR_FLAGS = [...new Set(FLAGS.filter((f) => f.kind === 'dir').flatMap((f) => [f.name, ...(f.alias && !f.alias.startsWith('--') ? [f.alias] : [])]))];
const FILE_FLAGS = [...new Set(FLAGS.filter((f) => f.kind === 'file').flatMap((f) => [f.name, ...(f.alias && !f.alias.startsWith('--') ? [f.alias] : [])]))];
const ALL_FLAG_WORDS = FLAGS.flatMap((f) => [f.name, ...(f.alias && f.alias.startsWith('--') ? [f.alias] : [])]);

function bash(): string {
  const dirCase = DIR_FLAGS.join('|');
  const fileCase = FILE_FLAGS.join('|');
  return `# bash completion for mdss (md-semantic-search)
# Generated by \`mdss completions bash\` (issue #107).
# Install: eval "$(mdss completions bash)"
_mdss_completion() {
  local cur prev commands flags
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  commands="${COMMANDS.join(' ')}"
  flags="${ALL_FLAG_WORDS.join(' ')}"

  case "$prev" in
    ${dirCase})
      mapfile -t COMPREPLY < <(compgen -d -- "$cur"); return 0 ;;
    ${fileCase})
      mapfile -t COMPREPLY < <(compgen -f -- "$cur"); return 0 ;;
  esac

  if [[ "$cur" == -* ]]; then
    mapfile -t COMPREPLY < <(compgen -W "$flags" -- "$cur")
    return 0
  fi

  if (( COMP_CWORD <= 2 )); then
    mapfile -t COMPREPLY < <(compgen -W "$commands" -- "$cur")
  fi
}
complete -o default -F _mdss_completion mdss md-semantic-search
`;
}

function zsh(): string {
  const cmdDescs = COMMANDS.map((c) => `'${c}'`).join(' ');
  return `#compdef mdss
# zsh completion for mdss — generated by \`mdss completions zsh\` (issue #107).
# Install: mkdir -p ~/.zfunc && mdss completions zsh > ~/.zfunc/_mdss
# (ensure ~/.zfunc is in fpath BEFORE compinit)
local -a commands options dir_flags file_flags
commands=(${cmdDescs})
options=(${ALL_FLAG_WORDS.map((f) => `'${f}'`).join(' ')})
dir_flags=(${DIR_FLAGS.map((f) => `'${f}'`).join(' ')})
file_flags=(${FILE_FLAGS.map((f) => `'${f}'`).join(' ')})

_mdss() {
  local cur prev
  cur="\${words[CURRENT]}"
  prev="\${words[CURRENT-1]}"
  if (( CURRENT == 2 )) && [[ "$cur" != -* ]]; then
    _describe -t commands 'mdss command' commands
    return
  fi
  if (( \${dir_flags[(Ie)$prev]} )); then
    _directories
    return
  fi
  if (( \${file_flags[(Ie)$prev]} )); then
    _files
    return
  fi
  if [[ "$cur" == -* ]]; then
    _describe -t options 'mdss option' options
    return
  fi
}
compdef _mdss mdss md-semantic-search
`;
}

function fish(): string {
  const lines: string[] = [
    '# fish completion for mdss — generated by `mdss completions fish` (issue #107).',
    '# Install: mdss completions fish > ~/.config/fish/completions/mdss.fish',
    '',
    `complete -c mdss -n '__fish_is_first_arg' -a '${COMMANDS.join(' ')}'`,
    '',
  ];
  const seenShorts = new Set<string>();
  for (const f of FLAGS) {
    const parts = ['complete -c mdss'];
    if (f.alias && !f.alias.startsWith('--') && !seenShorts.has(f.alias)) {
      parts.push(`-s ${f.alias.slice(1)}`);
      seenShorts.add(f.alias);
    }
    parts.push(`-l ${f.name.slice(2)}`);
    if (f.kind !== 'flag') parts.push('-r');
    if (f.kind === 'file') parts.push('-F');
    if (f.kind === 'dir') parts.push('-a "(__fish_complete_directories)"');
    lines.push(parts.join(' '));
  }
  return lines.join('\n') + '\n';
}

function powershell(): string {
  return `# PowerShell completion for mdss — generated by \`mdss completions powershell\` (issue #107).
# Install: paste into your $PROFILE (or dot-source it from there).
Register-ArgumentCompleter -CommandName 'mdss','md-semantic-search' -Native -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $commands = @('${COMMANDS.join("','")}')
  $dirFlags = @('${DIR_FLAGS.join("','")}')
  $fileFlags = @('${FILE_FLAGS.join("','")}')
  $flags = @('${ALL_FLAG_WORDS.join("','")}')

  $elements = @($commandAst.CommandElements)
  if ($elements.Count -le 1) {
    $commands | Where-Object { $_ -like "$wordToComplete*" } |
      ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'Command', $_) }
    return
  }

  $prev = ''
  if ($elements.Count -ge 2) { $prev = $elements[$elements.Count - 2].ToString() }

  if (($dirFlags -contains $prev) -or ($fileFlags -contains $prev)) {
    return # defer path completion to PowerShell's native provider
  }

  if ("$wordToComplete".StartsWith('-')) {
    $flags | Where-Object { $_ -like "$wordToComplete*" } |
      ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_) }
    return
  }

  if ($elements.Count -eq 2) {
    $commands | Where-Object { $_ -like "$wordToComplete*" } |
      ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'Command', $_) }
  }
}
`;
}

const GENERATORS: Record<CompletionShell, () => string> = { bash, zsh, fish, powershell };

/** Generate a self-contained completion script; throws on an unknown shell. */
export function generateCompletion(shell: string): string {
  const gen = GENERATORS[shell as CompletionShell];
  if (!gen) {
    throw new Error(`unknown shell "${shell}" — use one of: ${COMPLETION_SHELLS.join('|')}`);
  }
  return gen();
}
